services:
  - type: web
    name: jg-company-sync
    runtime: node
    plan: free
    region: oregon
    rootDir: sync_server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
