import 'streaming_account_model.dart';

/// ============================================================================
/// [MODELO / DATOS INICIALES] MockData
/// ============================================================================
/// Contiene los registros extraídos directamente de la hoja de Excel de
/// JG COMPANY S.A.S para que la aplicación inicie con información real.
/// ============================================================================
class MockData {
  static List<StreamingAccountModel> get initialAccounts {
    final now = DateTime.now();
    return [
      StreamingAccountModel(
        id: 'acc_001',
        proveedor: 'DIGITAL HOUSE',
        servicio: 'NETFLIX PA',
        cuenta: 'camelo321rd05g8-4@hotmail.com',
        clave: 'wy@8724neg',
        perfil: '1',
        pin: '2030',
        cliente: 'JHOANA SARMIENTO',
        telefono: '+573001234567',
        fechaCompra: DateTime(now.year, now.month, 20),
        fechaVencimiento: DateTime(now.year, now.month + 1, 20),
        vendedor: 'JUAN',
        estado: 'PAGO',
        valorVenta: 14000.0,
        valorCompra: 5000.0,
        notas: 'Cliente puntual en pagos',
      ),
      StreamingAccountModel(
        id: 'acc_002',
        proveedor: 'DIGITAL HOUSE',
        servicio: 'NETFLIX PA',
        cuenta: 'camelo321rd05g8-4@hotmail.com',
        clave: 'wy@8724neg',
        perfil: '2',
        pin: '2411',
        cliente: 'NELLYS GARCES',
        telefono: '+573109876543',
        fechaCompra: DateTime(now.year, now.month, 7),
        fechaVencimiento: DateTime(now.year, now.month + 1, 7),
        vendedor: 'JUAN',
        estado: 'PAGO',
        valorVenta: 14000.0,
        valorCompra: 5000.0,
        notas: 'Perfil individual',
      ),
      StreamingAccountModel(
        id: 'acc_003',
        proveedor: 'DIGITAL HOUSE',
        servicio: 'NETFLIX PA',
        cuenta: 'balasminh4@outlook.sa',
        clave: 'tt2005',
        perfil: '3',
        pin: '7/08/1906',
        cliente: 'DANNY LUZ',
        telefono: '+573155554321',
        fechaCompra: DateTime(now.year, now.month, 1),
        fechaVencimiento: DateTime(now.year, now.month + 1, 1),
        vendedor: 'JUAN',
        estado: 'PAGO',
        valorVenta: 14000.0,
        valorCompra: 5000.0,
        notas: 'Pantalla completa',
      ),
      StreamingAccountModel(
        id: 'acc_004',
        proveedor: 'DIGITAL HOUSE',
        servicio: 'NETFLIX PA',
        cuenta: 'camelo321rd05g8-4@hotmail.com',
        clave: 'wy@8724neg',
        perfil: '4',
        pin: '3030',
        cliente: 'KELLY TRESPALACIO',
        telefono: '+573201122334',
        fechaCompra: DateTime(now.year, now.month, 6),
        fechaVencimiento: DateTime(now.year, now.month + 1, 6),
        vendedor: 'JUAN',
        estado: 'PAGO',
        valorVenta: 14000.0,
        valorCompra: 5000.0,
        notas: 'Renovación mensual automática',
      ),
      StreamingAccountModel(
        id: 'acc_005',
        proveedor: 'S.G.R STREAMING',
        servicio: 'NETFLIX PA',
        cuenta: 'casagr011@gmail.com',
        clave: 'Casagr.011',
        perfil: '1',
        pin: '2011',
        cliente: 'CARLOS MENDOZA',
        telefono: '+573014455667',
        fechaCompra: DateTime(now.year, now.month, 12),
        fechaVencimiento: DateTime(now.year, now.month + 1, 12),
        vendedor: 'JUAN',
        estado: 'PAGO',
        valorVenta: 14000.0,
        valorCompra: 4500.0,
        notas: 'Proveedor S.G.R',
      ),
      StreamingAccountModel(
        id: 'acc_006',
        proveedor: 'S.G.R STREAMING',
        servicio: 'NETFLIX PA',
        cuenta: 'casagr011@gmail.com',
        clave: 'Casagr.011',
        perfil: '2',
        pin: '2911',
        cliente: 'ANDREA CASTRO',
        telefono: '+573123344556',
        fechaCompra: DateTime(now.year, now.month, 15),
        fechaVencimiento: DateTime(now.year, now.month + 1, 15),
        vendedor: 'JUAN',
        estado: 'PENDIENTE',
        valorVenta: 14000.0,
        valorCompra: 4500.0,
        notas: 'Pendiente transferencia Nequi',
      ),
      StreamingAccountModel(
        id: 'acc_007',
        proveedor: 'S.G.R STREAMING',
        servicio: 'PRIME VIDEO PA',
        cuenta: 'casagr011@gmail.com',
        clave: 'Casagr.011',
        perfil: '1',
        pin: '30952',
        cliente: 'MATEO RAMIREZ',
        telefono: '+573187766554',
        fechaCompra: DateTime(now.year, now.month, 10),
        fechaVencimiento: DateTime(now.year, now.month + 1, 10),
        vendedor: 'JUAN',
        estado: 'PAGO',
        valorVenta: 9000.0,
        valorCompra: 3000.0,
        notas: 'Prime Video Pantalla',
      ),
      StreamingAccountModel(
        id: 'acc_008',
        proveedor: 'S.G.R STREAMING',
        servicio: 'PRIME VIDEO PA',
        cuenta: 'casagr011@gmail.com',
        clave: 'Casagr.011',
        perfil: '2',
        pin: '29112',
        cliente: 'LAURA VARGAS',
        telefono: '+573179988776',
        fechaCompra: DateTime(now.year, now.month, 18),
        fechaVencimiento: DateTime(now.year, now.month + 1, 18),
        vendedor: 'JUAN',
        estado: 'PAGO',
        valorVenta: 9000.0,
        valorCompra: 3000.0,
        notas: '',
      ),
    ];
  }
}
